////
I'd say this section is a good place to give a very sparse high level idea of
what the synth is about, provide links to subsections, and provide a quickstart
////

ZynAddSubFX is a powerful multi-platform open-source software sound synthesizer.
Zyn provides a variety of sound creation options including 3 core synthesis
engines, 10+ filter options, lfos/envelopes for modulation, microtonal support,
multi-parameter automation support, as well as many other features.
Zyn can be run both as a standalone application as well as a VST/LV2/DSSI plugin
within your favorite DAW.
ZynAddSubFX can be controlled through multiple interfaces, though this manual
will focus on the new and powerful Zyn-Fusion interface.

=== About the User Manual

The Manual was divided into several sections:

Introduction:: is the first part of the Manual, we're starting with a few simple tutorials to get the user hands-on with the synthesizer as fast as possible.
Basic:: is the second part where we start to cover everything from top to bottom. If you're fairly new to Zyn-Fusion ,this part should provide you with a comprehensive, yet not overwhelming instruction.
Advanced:: the third part, where we go into more detail and cover things that were skipped in the previous part. More advanced users should benefit from this part, adding depth to their understanding of the synthesizer. For newcomers, this part might be too confusing.
Glossary:: this part is a glossary appendix with various terms indexed alphabetically
Routing Diagrams:: the last part is a set are signal routing diagrams that should let you gain a deep understanding of the inner workings of the synthesizer.

=== Quick start

link:QuickStart.adoc[Quick Start Guide ]

////
XXX Each one of these bullet points should be expanded upon somewhere else IMO

* Zyn-Fusion is actually three synthesizers in one box - they can play together
* multitimbral: can play multiple patches at once using different MIDI channels, or simply layer then together for complex sounds
* we can layers sounds like no one else (parts, kits, addsynth voices, multiple engines)
* Built in effects
* 16 macro slots for automation or live control - everything can be automated (unlike the old ZynAddSubFX interface)
////

=== Tutorial One: Kick Drum Synthesis
link:IntroTutorial-KickDrumSynthesis.adoc[Intro Tutorial - Kick Drum Synthesis]
