This section aims to introduce the user to Zyn-Fusion, using a few brief sentences and tutorials.

ZynAddSubFX is a powerful multi-platform open-source software sound synthesizer.
Zyn provides a variety of sound creation options including 3 core synthesis
engines, 10+ filter options, LFOs/envelopes for modulation, microtonal support,
multi-parameter automation support, as well as many other features.
Zyn can be run both as a standalone application as well as a VST/LV2/DSSI plugin
within your favorite DAW.

=== About the User Manual

// TODO: This manual aims to teach the user...
// Do this when everything else is finished

The Manual was divided into several sections:

Introduction:: We're starting with a few simple tutorials to get the user hands-on with the synthesizer as fast as possible.
Basic:: We start to cover everything from top to bottom. If you're fairly new to Zyn-Fusion, this part should provide you with a comprehensive, yet not overwhelming instruction.
Advanced:: We go into more detail and cover things that were skipped in the previous part. More advanced users should benefit from this part, adding depth to their understanding of the synthesizer. For newcomers, this part might be too confusing.
Glossary:: A glossary appendix with various terms indexed alphabetically
Routing Diagrams:: Signal routing diagrams that should let you gain a deep understanding of the inner workings of the synthesizer.

Even though ZynAddSubFX can be used as a standalone tool, the manual utilizes Ardour, primarily for it's session handling, ensuring that we can save and return to our progress at any time.

=== Quick start

include::QuickStart.adoc[]

////
TODO: Each one of these bullet points should be expanded upon somewhere else IMO

* Zyn-Fusion is actually three synthesizers in one box - they can play together
* multitimbral: can play multiple patches at once using different MIDI channels, or simply layer then together for complex sounds
* we can layers sounds like no one else (parts, kits, addsynth voices, multiple engines)
* Built in effects
* 16 macro slots for automation or live control - everything can be automated (unlike the old ZynAddSubFX interface)
////
